version: "3"
services:

  nginx:
    image: ${APP_NAME}_nginx
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        APP_UID: ${APP_UID}
        APP_GID: ${APP_GID}
        APP_USER: ${APP_USER}
        TZ: ${TZ}
    container_name: ${APP_NAME}_nginx_${APP_INSTANCE}
    restart: unless-stopped
    ports:
      - 127.0.0.1:${APP_PORT}:80
    depends_on:
      - php
    volumes:
      - ./config/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

  php:
    image: ${APP_NAME}_php
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        APP_UID: ${APP_UID}
        APP_GID: ${APP_GID}
        APP_USER: ${APP_USER}
        TZ: ${TZ}
    container_name: ${APP_NAME}_php_${APP_INSTANCE}
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

  database:
    image: mariadb:10.6.4
    container_name: ${APP_NAME}_database_${APP_INSTANCE}
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

#  database:
#    image: postgres:9.6.23-buster
#    container_name: ${APP_NAME}_database_${APP_INSTANCE}
#    restart: unless-stopped
#    volumes:
#      - ./data/postgresql:/var/lib/postgresql/data
#    env_file:
#      - .env
#      - .env.local
#    logging:
#      driver: json-file
#      options:
#        max-size: "1m"
#        max-file: "10"
