version: "3"
services:

  nginx:
    image: ${APP_NAME}_nginx
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        APP_UID: ${APP_UID}
        TZ: ${TZ}
    container_name: ${APP_NAME}_nginx_${APP_INSTANCE}
    restart: "no"
    ports:
      - ${APP_PORT}:80
    depends_on:
      - php
    volumes:
      - ./config/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

  php:
    image: ${APP_NAME}_php
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        APP_UID: ${APP_UID}
        TZ: ${TZ}
#        BLACKFIRE_ENABLE: ${BLACKFIRE_ENABLE}
    container_name: ${APP_NAME}_php_${APP_INSTANCE}
    restart: "no"
    depends_on:
      - database
#      - blackfire
    volumes:
      - ./config/php/php.local.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

  database:
    image: mariadb:10.6.3
    container_name: ${APP_NAME}_database_${APP_INSTANCE}
    restart: "no"
    ports:
      - 33306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

#  database:
#    image: postgres:9.6.22-buster
#    container_name: ${APP_NAME}_database_${APP_INSTANCE}
#    restart: "no"
#    ports:
#      - 54320:5432
#    volumes:
#      - ./data/postgresql:/var/lib/postgresql/data
#    env_file:
#      - .env
#      - .env.local
#    logging:
#      driver: json-file
#      options:
#        max-size: "1m"
#        max-file: "10"

#  blackfire:
#    image: blackfire/blackfire
#    container_name: ${APP_NAME}_blackfire_${APP_INSTANCE}
#    restart: "no"
#    env_file:
#      - .env
#      - .env.local
#    logging:
#      driver: json-file
#      options:
#        max-size: "1m"
#        max-file: "10"
