version: "3"
services:

  nginx:
    image: __dwsmyapp___nginx
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        APP_UID: ${APP_UID}
        APP_TZ: ${APP_TZ}
    container_name: __dwsmyapp___nginx_${APP_INSTANCE}
    restart: unless-stopped
    ports:
      - 127.0.0.1:${APP_PORT}:80
    links:
      - php
    volumes:
      - ./config/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

  php:
    image: __dwsmyapp___php
    build:
      context: ./
      dockerfile: .docker/php/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        APP_UID: ${APP_UID}
        APP_TZ: ${APP_TZ}
    container_name: __dwsmyapp___php_${APP_INSTANCE}
    restart: unless-stopped
    links:
      - database
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

  database:
    image: __dwsmyapp___mariadb
    build:
      context: ./
      dockerfile: .docker/mariadb/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
        APP_UID: ${APP_UID}
        APP_TZ: ${APP_TZ}
    container_name: __dwsmyapp___database_${APP_INSTANCE}
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - .env
      - .env.local
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
